import "./styles.css";
import "./styles/ui-skin.css";
import { wireInput1, wireInput2 } from "./ui/battle/input";
import { wireBoot1, wireBoot2, wireBoot3, wireBoot4 } from "./ui/boot";
import { wireCoach1 } from "./ui/coach";
import { wireCodex1, wireCodex2 } from "./ui/dialogs/codex";
import { wireCommon1 } from "./ui/dialogs/common";
import { wireConfirm1 } from "./ui/dialogs/confirm";
import { wireElementUpgrade1, wireElementUpgrade2 } from "./ui/dialogs/element-upgrade";
import { wireFormationUnlock1 } from "./ui/dialogs/formation-unlock";
import { wireHelp1, wireHelp2 } from "./ui/dialogs/help";
import { wireS131, wireS132 } from "./ui/dialogs/s13";
import { wireSettings1, wireSettings2, wireSettings3 } from "./ui/dialogs/settings";
import { wireDevTools1 } from "./ui/dev-tools";
import { wireHint1 } from "./ui/hint";
import { wireHotkeys1 } from "./ui/hotkeys";
import { wireHud1, wireHud2, wireHud3, wireHud4 } from "./ui/hud";
import { wireCasualFusion1 } from "./ui/panels/casual-fusion";
import { wireConcentration1 } from "./ui/panels/concentration";
import { wireEvolution1 } from "./ui/panels/evolution";
import { wireGoal1 } from "./ui/panels/goal";
import { wireGrowth1, wireGrowth2 } from "./ui/panels/growth";
import { wireInventory1 } from "./ui/panels/inventory";
import { wireSelected1, wireSelected2, wireSelected3 } from "./ui/panels/selected";
import { wireShop1 } from "./ui/panels/shop";
import { wireTalisman1 } from "./ui/panels/talisman";
import { wireS00Menu1, wireS00Menu2, wireS00Menu3, wireS00Menu4 } from "./ui/s00-menu";
import { wireSummonReveal1 } from "./ui/summon-reveal";
import { wireTutorial1 } from "./ui/tutorial";

wireBoot1();
wireHud1();
wireInput1();
wireInput2();
wireS131();
wireFormationUnlock1();
wireS132();
wireS00Menu1();
wireEvolution1();
wireS00Menu2();
wireS00Menu3();
wireShop1();
wireSummonReveal1();
wireHud2();
wireElementUpgrade1();
wireSelected1();
wireCasualFusion1();
wireElementUpgrade2();
wireHud3();
wireHelp1();
wireHelp2();
wireSettings1();
wireGrowth1();
wireSelected2();
wireSettings2();
wireCodex1();
wireCommon1();
wireConfirm1();
wireHud4();
wireGoal1();
wireInventory1();
wireConcentration1();
wireGrowth2();
wireCodex2();
wireSettings3();
wireTalisman1();
wireSelected3();
wireHotkeys1();
wireS00Menu4();
wireBoot2();
wireDevTools1();
wireCoach1();
wireHint1();
wireTutorial1();
wireBoot3();
wireBoot4();
